* Forest Dream video

This is an interactive music video for the song "forest dream":

https://soundcloud.com/joakimv/forest-dream

The song was made with overtone, so using Quil for the video seemed
like an interesting idea.



* Usage

The arrow keys change direction in the forest journey

a,v keys rotate the camera.

keys 1,2, etc produce scenes corresponding to the lyrics.
(basically its just an image that zooms by)

key 0 reset the scene. 


* Running
** from a shell
First of all, install Java, which is different depending on your
platform.

Then install Leiningen: https://leiningen.org/

Now when you have Java and Leiningen you should be able to run the application:

lein run -m my-sketch.core



** from Emacs
Emacs - run cider, open `core.clj` and press `C-c C-k` to evaluate the file.


* License

Copyright © Joakim Verona 2017

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.

(Actually I'm more of a GPL kind of guy, but it would seem GPL is hard
with Clojure code)
